services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: task_tracker_db
      POSTGRES_USER: task_tracker_user
      POSTGRES_PASSWORD: tasktrackerpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-task_tracker_user}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn task_tracker.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000:8000"
    environment:
      - POSTGRES_DB=task_tracker_db
      - POSTGRES_USER=task_tracker_user
      - POSTGRES_PASSWORD=tasktrackerpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: